[package]
name = "linfa"
version = "0.1.0"
authors = ["Luca Palmieri <>"]
description = "A Machine Learning framework for Rust"
license = "MIT/Apache-2.0"

[dependencies]
ndarray = "0.11.0"
num-traits = { version = "0.1.32", default-features = false }
